// PDF export utility
import html2pdf from "html2pdf.js";

export const exportSummaryAsPDF = async (
  summary: string,
  recordingTitle: string,
  onError?: (error: string) => void
) => {
  try {
    const element = document.createElement("div");
    element.innerHTML = `
      <div style="font-family: Arial, sans-serif; padding: 20px;">
        <h1 style="color: #1f2937; margin-bottom: 10px;">AI Summary</h1>
        <h2 style="color: #6b7280; font-size: 18px; margin-bottom: 20px;">${recordingTitle}</h2>
        <div style="color: #374151; line-height: 1.6;">
          ${summary
            .split("\n")
            .map((line) => `<p>${line}</p>`)
            .join("")}
        </div>
        <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af;">
          <p>Generated by Lecturely - ${new Date().toLocaleString()}</p>
        </div>
      </div>
    `;

    const opt = {
      margin: 10,
      filename: `summary-${recordingTitle}-${new Date().getTime()}.pdf`,
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { orientation: "portrait", unit: "mm", format: "a4" },
    };

    html2pdf().set(opt).from(element).save();
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : "Unknown error";
    if (onError) {
      onError(errorMsg);
    } else {
      console.error("Failed to export PDF:", errorMsg);
    }
  }
};
